SRC=XMLMain.hs XMLTypes.hs Play.hs solution.hs ../grade.hs  gradehw1.hs \
    ${GRADEDIR}/Mine.hs ${GRADEDIR}/hw1.hs

all:
	ghc -i/Users/pmr/src/SOE/src -odir ${GRADEDIR} -o ${GRADEDIR}/gradehw1 --make ${SRC}
